config/routes.rb
Rails.application.routes.draw do
  
  root to: redirect('/photos')
  resources :photos do
    get 'twitter_create'
  end

  get '/auth/:provider/callback', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ApplicationRecord
  mount_uploader :picture, PictureUploader

  
  validates :title, presence: true
  validates :title, length: { in: 1..30 } 

  validates :picture, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  def self.find_or_create_from_auth(auth)
    provider = auth[:provider]
    uid = auth[:uid]
    user_name = auth[:info][:user_name]
    consumer_key = auth.extra.access_token.consumer.key
    consumer_secret = auth.extra.access_token.consumer.secret
    token = auth.extra.access_token.token
    secret = auth.extra.access_token.secret

    self.find_or_create_by(provider: provider, uid: uid) do |user|
      user.user_name = user_name
      user.consumer_key = consumer_key
      user.consumer_secret = consumer_secret
      user.token = token
      user.secret = secret
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?

  private

  def current_user
    return unless session[:user_id]
    @current_user ||= User.find(session[:user_id])
  end

  def logged_in?
    !!session[:user_id]
  end

  def authenticate
    return if logged_in?
    redirect_to root_path, alert: "ログインしてください"
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :edit, :update, :destroy, :twitter_create]
  before_action :twitter_client, only: [:twitter_create]

  # GET /photos
  # GET /photos.json
  def index
    @photos = Photo.all.order(created_at: :desc)
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
  end

  # GET /photos/new
  def new
    @photo = Photo.new
  end

  # GET /photos/1/edit
  def edit
  end

  # POST /photos
  # POST /photos.json
  def create

    @photo = Photo.new(photo_params)

    respond_to do |format|
      if @photo.save
        format.html { redirect_to photos_path, notice: '写真のアップロードできました！' }
        format.json { render :index, status: :created }
      else
        format.html { render :new }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photos/1
  # PATCH/PUT /photos/1.json
  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { render :show, status: :ok, location: @photo }
      else
        format.html { render :edit }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to photos_url, notice: 'Photo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def twitter_create
    media_url = File.join(root_url(only_path: false), @photo.picture_url)
    media = open(media_url)
    @client.update_with_media("テスト", media) if @client
    flash[:notice] = "#{@photo.title} をつぶやきました。"

    redirect_to root_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id] || params[:photo_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_params
      params.require(:photo).permit(:title, :picture)
    end

   def twitter_client
     return @client = nil if session[:user_id].blank?

     user = User.find(session[:user_id])
     @client = Twitter::REST::Client.new do |config|
       config.consumer_key = user.consumer_key
       config.consumer_secret = user.consumer_secret
       config.access_token = user.token
       config.access_token_secret = user.secret
     end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_or_create_from_auth(request.env['omniauth.auth'])
    session[:user_id] = user.id
    flash[:notice] = "TwitterIDでログインしました。"

    redirect_to root_path
  end

  def destroy
    reset_session
    flash[:notice] = "ログアウトしました。"
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UnifaPhoto</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div>
      <% if logged_in? %>
        <li><%= link_to 'ログアウト', logout_path  %></li>
      <% else %>
        <li><%= link_to 'Twitterでログイン', '/auth/twitter' %></li>
      <% end %>
    </div>
    <div class="container">
      <% flash[:notice] if flash[:notice] %>
    </div>

    <%= yield %>
  </body>
</html>

app/views/photos/_form.html.erb
<%= form_with(model: photo, local: true, html: { multipart: true }) do |form| %>
  <% if photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(photo.errors.count, "件") %> のエラーがあります。</h2>

      <ul>
      <% photo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :タイトル（必須）30文字以内 %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :アップロードする写真 %>
    <%= form.file_field :picture %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/photos/_photo.html.erb
<tr>
  <td><%= photo.title %></td>
  <td><%= I18n.l(photo.updated_at) %></td>
  <td><%= link_to image_tag(photo.picture_url, width: 300), photo if photo.picture.present? %></td>
  <td>
    <%= logged_in? ? (link_to 'Tweet', photo_twitter_create_path(photo.id)) : "Tweetする場合は、左上からログインしてください" %>
  </td>
  <td><%= link_to '詳細ページ', photo %></td>
  <td><%#= link_to 'Edit', edit_photo_path(photo) %></td>
  <td><%= link_to '削除する', photo, method: :delete, data: { confirm: '削除してよろしいですか?' } %></td>
</tr>

app/views/photos/edit.html.erb
<h1>Editing Photo</h1>

<%= render 'form', photo: @photo %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

app/views/photos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>写真一覧</h1>

<%= link_to '写真をアップロードする', new_photo_path %>

<hr>
<table>
  <thead>
    <tr>
      <th>タイトル</th>
      <th>作成日</th>
      <th>アップロード画像</th>
      <th>SNS</ht>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <th colspan="4">
        <%= @photos.present? ? render(@photos) : "アップロードされた写真はありません" %>
      </th>
    </tr>
  </tbody>
</table>

app/views/photos/new.html.erb
<h1>写真アップロード</h1>

<%= render 'form', photo: @photo %>

<%= link_to 'もどる', photos_path %>

app/views/photos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @photo.title %>
</p>

<p>
  <strong>Picture:</strong>
  <%= image_tag(@photo.picture_url, width: 600) if @photo.picture.present? %>
</p>

<%= link_to 'Edit', edit_photo_path(@photo) %> |
<%= link_to 'Back', photos_path %>